from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage
from PyQt5.QtCore import Qt


class Interface(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setup_ui()
        self.show()

    def setup_ui(self):
        self.setObjectName("MainWindow")
        self.resize(339, 432)
        self.centralwidget = QtWidgets.QWidget(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_buttons_canvas = QtWidgets.QFrame(self.centralwidget)
        self.frame_buttons_canvas.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_buttons_canvas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_canvas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_canvas.setObjectName("frame_buttons_canvas")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_buttons_canvas)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_pen_mode = QtWidgets.QPushButton(self.frame_buttons_canvas)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/карандаш.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon.addPixmap(QtGui.QPixmap("src"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_pen_mode.setIcon(icon)
        self.pushButton_pen_mode.setObjectName("pushButton_pen_mode")
        self.horizontalLayout.addWidget(self.pushButton_pen_mode)
        self.pushButton_clear_mode = QtWidgets.QPushButton(self.frame_buttons_canvas)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/ластик.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clear_mode.setIcon(icon1)
        self.pushButton_clear_mode.setObjectName("pushButton_clear_mode")
        self.horizontalLayout.addWidget(self.pushButton_clear_mode)
        self.pushButton_clear_all = QtWidgets.QPushButton(self.frame_buttons_canvas)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/очистить2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clear_all.setIcon(icon2)
        self.pushButton_clear_all.setObjectName("pushButton_clear_all")
        self.horizontalLayout.addWidget(self.pushButton_clear_all)
        self.verticalLayout.addWidget(self.frame_buttons_canvas)
        self.frame_canvas = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_canvas.sizePolicy().hasHeightForWidth())
        self.frame_canvas.setSizePolicy(sizePolicy)
        self.frame_canvas.setMaximumSize(QtCore.QSize(1000, 128))
        self.frame_canvas.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_canvas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_canvas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_canvas.setObjectName("frame_canvas")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_canvas)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addWidget(self.frame_canvas)
        self.frame_buttons_detect = QtWidgets.QFrame(self.centralwidget)
        self.frame_buttons_detect.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_buttons_detect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_detect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_detect.setObjectName("frame_buttons_detect")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_buttons_detect)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_detect = QtWidgets.QPushButton(self.frame_buttons_detect)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/распознать.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_detect.setIcon(icon3)
        self.pushButton_detect.setObjectName("pushButton_detect")
        self.horizontalLayout_2.addWidget(self.pushButton_detect)
        self.pushButton_train = QtWidgets.QPushButton(self.frame_buttons_detect)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/обучить.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_train.setIcon(icon4)
        self.pushButton_train.setObjectName("pushButton_train")
        self.horizontalLayout_2.addWidget(self.pushButton_train)
        self.verticalLayout.addWidget(self.frame_buttons_detect)
        self.frame_labels = QtWidgets.QFrame(self.centralwidget)
        self.frame_labels.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_labels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_labels.setObjectName("frame_labels")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_labels)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_output = QtWidgets.QLabel(self.frame_labels)
        self.label_output.setOpenExternalLinks(False)
        self.label_output.setObjectName("label_output")
        self.verticalLayout_2.addWidget(self.label_output)
        self.verticalLayout.addWidget(self.frame_labels)
        self.setCentralWidget(self.centralwidget)

        self.retranslate_ui()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_pen_mode.setText(_translate("MainWindow", "карандаш"))
        self.pushButton_pen_mode.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.pushButton_clear_mode.setText(_translate("MainWindow", "ластик"))
        self.pushButton_clear_mode.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.pushButton_clear_all.setText(_translate("MainWindow", "очистить"))
        self.pushButton_clear_all.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.pushButton_detect.setText(_translate("MainWindow", "распознать"))
        self.pushButton_detect.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.pushButton_train.setText(_translate("MainWindow", "обучить"))
        self.pushButton_train.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.label_output.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = Interface()
    sys.exit(app.exec_())
